name: Cybersecurity Daily Digest

# ── Triggers ────────────────────────────────────────────────────────────────
on:
  schedule:
    # 09:15 IST daily → 03:45 UTC (GitHub uses UTC)
    - cron: '40 8 * * *'
  workflow_dispatch:   # manual “Run workflow” button

# ── Job definition ──────────────────────────────────────────────────────────
jobs:
  post-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        env:
          TG_TOKEN:        ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID:      ${{ secrets.TG_CHAT_ID }}
          GENAI_API_KEY:   ${{ secrets.GENAI_API_KEY }}
          TWITTERAPI_KEY:  ${{ secrets.TWITTERAPI_KEY }}
        run: python bot/agent.py

